version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hoffmagic
      - POSTGRES_PASSWORD=hoffmagic
      - POSTGRES_DB=hoffmagic
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoffmagic"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    # Use the image built by 'nix build .#dockerImage'
    image: hoffmagic:latest # <<< CHANGE THIS
    # build: # <<< REMOVE THIS section
    #   context: .
    #   dockerfile: Dockerfile
    #   target: final

    volumes:
      # Mount content directory - Recommended over copying into image
      # Allows content changes without rebuilding the image
      # Adjust the source path if your content lives elsewhere (e.g., ./content)
      - ./src/content:/app/content

    environment:
      # Pass sensitive or environment-specific config here
      - DATABASE_URL=postgresql+psycopg://hoffmagic:hoffmagic@db:5432/hoffmagic
      # !!! CHANGE IN PRODUCTION !!! Use secrets management.
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key_change_in_production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-'["localhost", "127.0.0.1"]'}
      - DEBUG=${DEBUG:-true} # Default to true for compose, override for prod
      - ENV=${ENV:-development}

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
    # command: ["/docker-entrypoint.sh"] # Not needed if ENTRYPOINT is set correctly in flake.nix

volumes:
  postgres_data:
